# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stopage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('lattitude', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
            ],
        ),
    ]
