# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(max_length=120)),
                ('cost', models.DecimalField(decimal_places=2, default=10, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('busoptions', models.ManyToManyField(to='route.BusOption')),
                ('dest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dest', to='route.Stopage')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='route.Stopage')),
            ],
        ),
    ]
