# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0002_busoption_edge'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='best_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='best_option', to='route.BusOption'),
        ),
        migrations.AlterField(
            model_name='edge',
            name='busoptions',
            field=models.ManyToManyField(blank=True, null=True, to='route.BusOption'),
        ),
    ]
