# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0003_auto_20160515_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='busoptions',
            field=models.ManyToManyField(blank=True, to='route.BusOption'),
        ),
    ]
