# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0004_auto_20160515_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edge',
            name='busoptions',
        ),
        migrations.AddField(
            model_name='busoption',
            name='edges',
            field=models.ManyToManyField(blank=True, to='route.Edge'),
        ),
        migrations.AlterField(
            model_name='busoption',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
    ]
