# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0005_auto_20160515_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='stopage',
            name='adjacent',
            field=models.ManyToManyField(blank=True, related_name='_stopage_adjacent_+', to='route.Stopage'),
        ),
    ]
