# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0006_stopage_adjacent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='distance',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
    ]
