# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0007_auto_20160516_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='stopage',
            name='cost_from_source',
            field=models.DecimalField(decimal_places=6, default=100000000, max_digits=20),
        ),
    ]
