# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0008_stopage_cost_from_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='stopage',
            name='is_visited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stopage',
            name='previous_stopage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='route.Stopage'),
        ),
    ]
