# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0009_auto_20160516_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stopage',
            name='cost_from_source',
        ),
    ]
