# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0011_auto_20160516_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='jam_factor',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
    ]
